bybit:
  api_key: "KEN0Ic8O7D9keqTTMF65"
  api_secret: "eW4iCtH2r3dOK8UpHwJECFXrfIj02UNsjSh2"
  arbitrage_difference: 0.5
  request_interval: 3

telegram:
  bot_token: "7048405854:AAGtvFrF__IvhzmxllTs0SYmFCWvEh26HAM"
  chat_id: "8351713346"
