exchanges:
  bybit:
    api_key: "YOUR_BYBIT_API_KEY"
    api_secret: "YOUR_BYBIT_API_SECRET"
    min_volume: 100000
    enabled: true
    request_interval: 2
  # ...інші біржі
arbitrage_difference: 1.0
request_interval: 3
telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
  chat_id: "YOUR_TELEGRAM_CHAT_ID"